blank_issues_enabled: true
contact_links:
  - name: Nomi Discord
    url: https://discord.com/invite/zwQzqP8b6q
    about: Join us on Discord to discuss questions, gameplay advice, bugs, beta releases, and more.
